### ISSUE TITLE
Plotly says "double click to zoom back out" but you can't do this

### ISSUE THREAD

**Issue by theosanderson** [publichealthengland/coronavirus-dashboard#286] opened 2020-12-15 01:02 UTC
**Describe the bug**
When you zoom in on any graph Plotly says "double click to zoom back out", but you can't actually do this

**To Reproduce**
Go to a graph e.g. the top one here https://coronavirus.data.gov.uk/details/deaths (I was using Chrome on a PC)
Drag a box to zoom in on the graph
Observe tooltip (on first zoom)
Double click and observe no effect

**What happens**
A tooltip saying "double click to zoom back out appears. But double clicking has no effect.

**Additional context**
I think one removes tooltip like this: https://community.plotly.com/t/disable-double-click-unzoom/2630/4 (or could add the double-click behaviour)

**Comment by xenatisch** [comment] 2020-12-19 11:01
I'm afraid I cannot reproduce this on Mac. I have also not received any reports on the issue from other users. 

Chrome does have a tenancy to behave in unusual ways depending on the build and possibly even the extensions that are installed on it. 

I'll ask colleagues to reproduce this on Windows, but it sounds like an issue for [Plotly.js](https://github.com/plotly/plotly.js/) to investigate. 

![Screen Recording 2020-12-19 at 10 43 30](https://user-images.githubusercontent.com/13240654/102687595-0d857400-41e8-11eb-8e0d-34a588189e61.gif)

In the meantime, you should be able to use the "home" icon in the mode bar of the graph to reset it. 

<img width="392" alt="Screenshot 2020-12-19 at 10 52 32" src="https://user-images.githubusercontent.com/13240654/102687722-e4191800-41e8-11eb-83c4-425edb9fb0a4.png">

I am closing the issue for now, but please feel free to reopen it if you feel like the problem is from our end or you have any additional info.

**Closed by xenatisch** 2020-12-19 11:01 UTC
Labels: bug

**Comment by jenniferjfu2** [comment] 2022-12-05 00:25
I have the same issue on macOS Big Sur.
