### ISSUE TITLE
Make the dashboard work (possibly without map or graphs?) without javascript

### ISSUE THREAD

**Issue by frankieroberto** [PublicHealthEngland/coronavirus-dashboard#15] opened 2020-04-15 10:33 UTC
Great (fast!) work on this!

It'd be great it if could work without javascript somehow - eg at least showing the figures and the tables.

Currently it displays this:

<img width="1241" alt="Screenshot 2020-04-15 at 11 30 45" src="https://user-images.githubusercontent.com/30665/79327696-d0583c00-7f0c-11ea-95aa-4db3fe6a9bf8.png">

**Comment by xenatisch** [comment] 2020-04-15 16:07
That's unfortunately impossible. The entire service has been implemented in JavaScript (not just the map).

**Comment by dracos** [comment] 2020-04-19 11:03
http://www.dracos.co.uk/made/coronavirus.data.gov.uk/ - doesn't seem impossible.

**Comment by xenatisch** [comment] 2020-04-19 18:58
I am reopening the issue because several members of our team have now been assigned to design a static version of the site.

**Comment by xenatisch** [comment] 2020-04-19 19:01
@dracos, By impossible, I meant that we did not have resources allocated to it at the time, nor did we have it an a priority. Now we do, so we're getting there.

**Comment by Ha-san-ali** [comment] 2020-04-19 20:12
![](https://github.trello.services/images/mini-trello-icon.png) [Does not work with javascript turned off. We need a fallback option.](https://trello.com/c/mS3s4WiE/134-does-not-work-with-javascript-turned-off-we-need-a-fallback-option)

**Closed** 2020-05-28 23:31 UTC
Labels: enhancement, wontfix

**Comment by dracos** [comment] 2020-05-29 07:46
Any chance of an explanation?

**Comment by xenatisch** [comment] 2020-05-29 08:54
Hi @dracos. I agree with you on that, but we are moving on to another structure, which is is pretty much entirely dependent on a new API service that we have designed. It is extremely dynamic, and 95% of the contents are visualisations. No tables, just a few numbers, and the rest are graphs and maps. I cannot justify creating a backend for it just to show a few numbers which are not even location specific. It'll increase the latency, the cost, and the development time. 

It might not take long to develop, in fact it wouldn't, but we have to serve hundreds to thousands of requests a minute with minimal latency, using real time data. I cannot cache the pages either, because CDN caching would mean changes to the data are not reflected in real time (purging the CDN cache takes a while). I am not convinced that at this point, and based on our design, we would be able to provide anything useful without JavaScript... unless you're interested in the overall numbers, which to be fair, you can get from lots of different sources at this point. I have to find a balance between development time, usability of the service, complexity and cost. 

The type of crash we see in #172 will now be handled via the #171 solution. It's really rare though, and this time it was caused by a change in our file system, making the existing patterns obsolete.

Again, I agree that JS-only makes the site more fragile. I am no fan of JS only services myself. But let's be realistic, this is a service to visualise the data (soon) provide an interactive experience. We can't really have that without JavaScript. 

We'll probably launch the Beta version of our new service some time next week. I am happy to consider your suggestions on how to make it (more) static then.
