### ISSUE TITLE
Add gzip (or similar) to data_latest.json

### ISSUE THREAD

**Issue by dracos** [publichealthengland/coronavirus-dashboard#62] opened 2020-04-25 12:08 UTC
The server serving data_latest.json is not sending out a compressed file, which would reduce the current data file request (as I write) from 575K to something more like 54K.

**Comment by xenatisch** [comment] 2020-04-25 12:59
@dracos That's going through the CDN directly from the storage. I need to check the configs to see what can be done.

**Comment by xenatisch** [comment] 2020-04-26 23:14
I have now investigated this issue. Almost all of the files are compressed, except for this one. It appears as though the storage determines its `content-type` as `octet-stream` (binary) for some reason, and as such bypasses the compression protocol. 

I have no idea why that's happening as all other JSON files appear to have the correct `content-type` associated with them.

It is possible to override it in the CDN rules, but that's a fix which does not address the issue. I'm going to find out why this is happening in the first place.

**Comment by Ha-san-ali** [comment] 2020-04-27 15:10
![](https://github.trello.services/images/mini-trello-icon.png) [Add gzip (or similar) to data_latest.json](https://trello.com/c/Qybt3ZRa/322-add-gzip-or-similar-to-datalatestjson)

**Comment by acme** [comment] 2020-04-29 13:54
Another way to make the JSON file smaller would be to remove unnecessary whitespace, e.g.:

```bash
$ cat data_latest.json | jq --compact-output > data_latest_compact.json
$ ls -lh data_latest.json data_latest_compact.json
-rw-r--r--  1 acme  acme   1.6M 28 Apr 19:14 data_latest.json
-rw-r--r--  1 acme  acme   1.4M 29 Apr 14:47 data_latest_compact.json
$ gzip -9 data_latest.json; gzip -9 data_latest_compact.json
$ ls -lh data_latest.json.gz data_latest_compact.json.gz
-rw-r--r--@ 1 acme  acme   127K 28 Apr 19:14 data_latest.json.gz
-rw-r--r--  1 acme  acme   122K 29 Apr 14:47 data_latest_compact.json.gz
```

**Comment by xenatisch** [comment] 2020-05-03 13:10
@acme I'm working on it. Re white spaces, I'm not sure which ones you're referring to. The files should be minified. So I'm assuming you're referring to the space after commas and stuff. Are we sure that doesn't end up causing any encoding issues on some old browser?

**Comment by acme** [comment] 2020-05-03 19:03
For example, https://c19downloads.azureedge.net/downloads/data/data_latest.json includes many 

`{"date": "2020-04-02", "value": 652}`

... which could instead be:

`{"date":"2020-04-02","value":652}`

[ECMA-404 The JSON Data Interchange Standard](http://seriot.ch/parsing_json.php) says:
> Insignificant whitespace is allowed before or after any token

[Parsing JSON is a Minefield](http://seriot.ch/parsing_json.php), but all parsers should be able to handle parsing without that insignificant whitespace.

Compressing the response with gzip will save more bandwidth.

**Comment by xenatisch** [comment] 2020-05-03 23:36
@acme There is more to this than most people see from the outside. Some people think that because this is a frontend service, there's no backend associated with it either. That's not true at all. We have multiple severs and serverless functions dealing with different parts of the service.

The issue is, all our CDNs (and we have several) and our servers are set to compress any file with the content type of `application/json` or `text/csv`. Now, they do that most of the times, but there are two issues:

1. The main data file is deployed through a data pipeline directly to our Azure storage. For some bizarre reason, the content type is then determined as `application/octet-stream` (i.e. binary file), whose type is not compressed by the CDN. I can't just make a rule there for this content type, it'd confused some platforms. Another hassle is that when the content type is incorrect, the data won't bypass CDN caching, so we sometimes need to purge the CDN cache manually too. 

2. Even when manually set to `application/json`, the CDN sometimes bypasses the compression rule. I'm trying to find out why, but I don't have much time to investigate these things in as much depth as I would like to - not right now.

Additionally, our end to end latency is very low (5-20ms on average). It'd be kinder to the overall network if the load was reduced, and believe you me, we do care. The main Dev and DevOps is currently a little... shall we say stretched and this is not a high priority issue. That doesn't, however, mean that I am not actively pocking around looking for a solution. But it's a maze, and I don't want to bring the whole thing down by experimenting on stuff.

The initial design and structuring was not done by us - we inherited it after the initial deployment. Bear in mind that this is a crisis response service. It is a bit different to your average service which undergoes months of planning, service design, user research, etc. This had to be done fast, not necessarily pretty. We are reading 100s of emails (not to mention twitter threads) everyday, and evaluate every single feedback to enhance the service; but some features have higher priorities. Some of us have been working on this for 70-90 hours a week to get it here. 

Finally, I'm going to split the data down to multiple files for the main service (not the downloads) via a [separate ETL](https://github.com/PublicHealthEngland/coronavirus-dashboard-pipeline-etl) that I have written and deployed. That would not necessarily solve the issue in its entirety, but it'll download parts of the data (mainly the heavier ones) on demand. It'll also not be a an entirely blocking process that prevents the service from loading altogether. The ETL is already splitting the data, and the structure will be incorporated into the frontend in the next few days.

At some point, I'll incorporate manually storage into the ETL. That'll give me the ability to change the metadata and correct the content type.  

As for the spaces, I'm a bit weary because we need to support IE. I'll change it and deploy it to our dev service so that our testers can test it on different platforms and browsers and if it is properly parsed everywhere, I'll add it to the ETL. Not sure if there's a Python library for it, but if not, I'll write some RegEx to do the work.

**Comment by dracos** [comment] 2020-05-04 06:57
`dumps(separators=(',',':'))`

**Comment by xenatisch** [comment] 2020-05-04 11:38
@dracos Thanks. I'd never really look at that argument.

**Comment by xenatisch** [comment] 2020-05-04 11:45
@dracos @acme I have now implemented the [removal of excess space chars from JSON outputs](https://github.com/PublicHealthEngland/coronavirus-dashboard-pipeline-etl/commit/6dcd825837359c1f268c07efe90bbeffe44a1090). It'll take effect from the next deployment of the data (some time this afternoon).

**Closed** 2021-05-08 09:26 UTC
Labels: enhancement
